# This file is part of GoAddons, which is licensed under the GNU General Public License v3.0.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.

version: '3.1'

services:
  goaddons_cdp:
    image: chromedp/headless-shell
    container_name: goaddons_cdp
    ports:
      - "9222:9222"
    volumes:
      - goaddons-addons-volume:/home/[YOUR_HOST_NAME_HERE]/Downloads/goaddons_download
      - goaddons-extract-volume:/home/[YOUR_HOST_NAME_HERE]/Downloads/goaddons_extract

volumes:
  kaasufouji-addons-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/[YOUR_HOST_NAME_HERE]/Downloads/goaddons_download
      o: bind
  kaasufouji-extract-volume:
    driver: local
    driver_opts:
      type: none
      device: "/home/[YOUR_HOST_NAME_HERE]/ssd/Games/battlenet/drive_c/Program Files (x86)/World of Warcraft/_retail_/Interface/AddOns"
      o: bind
